name: code-pipeline-sync-local


on: [push]

jobs:
  feature-branch-build:
   if: (startsWith(github.ref, 'refs/heads/feature/'))
   runs-on: [self-hosted]
   env:
      Win_Topaz_Location: 'C:\TWB-230101\WorkbenchCLI'
   steps:
      - name: checkout step
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}      
      - name: sync step
        uses: bmc-compuware/ispw-sync-local@ZENG-318739
        id: sync
        with:
          host: 'cwcc.bmc.com'
          port: 16196
          uid: 'PFHMKS0'
          #pass: ${{ secrets.TSO_TOKEN }}
          pass: 'gocwcc70'
          runtimeConfiguration: 'ICCGA'
          stream: 'GITFLOW'
          application: 'GITFLOWD'
          subAppl: 'GITFLOWD'
          checkoutLevel: 'FEAT'
          gitUid: 'msingh9999'
          #gitToken:  ${{ secrets.GH_TOKEN }}
          gitToken: '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'
          winTopazPath: ${{ env.Win_Topaz_Location }}
          containerCreation: 'per-branch'
          showEnv: true
          assignmentPrefix: 'GFLD'
          ispwConfigPath: 'GenApp_MainframeCore\ispwconfig.yml'
      
      - name: Build
        uses: bmc-compuware/ispw-build@v1
        id: build
        with:
          ces_url: 'http://aus-bdc-cwcc.bmc.com:2020/'
          ces_token: ${{ secrets.CES_TOKEN }}
          srid: 'ispw'
          runtime_configuration: 'ICCGA'
          build_automatically: ${{ steps.sync.outputs.automaticBuildJson }}
      - name: Get the number of build failures
        run: echo "The number of build failures is ${{ steps.build.outputs.generate_failed_count }}"

  release-branch-build:
   if: (startsWith(github.ref, 'refs/heads/release/'))
   runs-on: [self-hosted]
   env:
    Win_Topaz_Location: 'C:\TWB-230101\WorkbenchCLI'
   steps:
      - name: checkout step
        uses: actions/checkout@v3
        run: |  
            git pull --no-rebase
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          
      - name: sync step
        uses: bmc-compuware/ispw-sync-local@ZENG-318739
        id: sync
        with:
          host: 'cwcc.bmc.com'
          port: 16196
          uid: 'PFHMKS0'
          #pass: ${{ secrets.TSO_TOKEN }}
          pass: 'gocwcc70'
          runtimeConfiguration: 'ICCGA'
          stream: 'GITFLOW'
          application: 'GITFLOWD'
          subAppl: 'GITFLOWD'
          checkoutLevel: 'RLSE'
          gitUid: 'msingh9999'
          #gitToken:  ${{ secrets.GH_TOKEN }}
          gitToken: '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'
          winTopazPath: ${{ env.Win_Topaz_Location }}
          containerCreation: 'per-branch'
          showEnv: true
          assignmentPrefix: 'GFLD'
          ispwConfigPath: 'GenApp_MainframeCore\ispwconfig-nosb.yml'
      
      - name: Build
        uses: bmc-compuware/ispw-build@v1
        id: build
        with:
          ces_url: 'http://aus-bdc-cwcc.bmc.com:2020/'
          ces_token: ${{ secrets.CES_TOKEN }}
          srid: 'ispw'
          runtime_configuration: 'ICCGA'
          build_automatically: ${{ steps.sync.outputs.automaticBuildJson }}
      - name: Get the number of build failures
        run: echo "The number of build failures is ${{ steps.build.outputs.generate_failed_count }}"
